ALTER TYPE "SupportedGame" ADD VALUE 'DIAMOND';
ALTER TYPE "SupportedGame" ADD VALUE 'PEARL';
ALTER TYPE "SupportedGame" ADD VALUE 'PLATINUM';
ALTER TYPE "SupportedGame" ADD VALUE 'HEARTGOLD';
ALTER TYPE "SupportedGame" ADD VALUE 'SOULSILVER';
